from enum import Enum

class Footers(str, Enum):        
    THEMETAMORPHOSIS_EN = "*** END OF THE PROJECT GUTENBERG EBOOK METAMORPHOSIS ***"
    THEMETAMORPHOSIS_DE = "*** END OF THIS PROJECT GUTENBERG EBOOK DIE VERWANDLUNG ***"
    CRIMEANDPUNISHMENT_EN = "*** END OF THE PROJECT GUTENBERG EBOOK CRIME AND PUNISHMENT ***"
    CRIMEANDPUNISHMENT_ES = "*** END OF THIS PROJECT GUTENBERG EBOOK EL CRIMEN Y EL CASTIGO ***"