from enum import Enum

class Headers(str, Enum):        
    THEMETAMORPHOSIS_EN = "*** START OF THE PROJECT GUTENBERG EBOOK METAMORPHOSIS ***"
    THEMETAMORPHOSIS_DE = "*** START OF THIS PROJECT GUTENBERG EBOOK DIE VERWANDLUNG ***"
    CRIMEANDPUNISHMENT_EN = "*** START OF THE PROJECT GUTENBERG EBOOK CRIME AND PUNISHMENT ***"
    CRIMEANDPUNISHMENT_ES = "*** START OF THIS PROJECT GUTENBERG EBOOK EL CRIMEN Y EL CASTIGO ***"
    